.PHONY: all clean

all: lua/nibiru_core.so nibiru

lua/nibiru_core.so: src/libnibiru.c
	mkdir -p lua
	$(CC) $(CFLAGS) -fPIC -shared -o $@ $< -llua

nibiru: src/main.c
	$(CC) $(CFLAGS) -o $@ $< -llua

clean:
	rm -f lua/nibiru_core.so nibiru
